swagger: "2.0"
info:
  description: "Wallet service API"
  version: "0.0.1"
  title: "Wallet service"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /api/v1/accounts/all:
    get:
      summary: Get All accounts
      description: Get all available accounts
      produces:
      - application/json
      responses:
        200:
          description: Documentation page
          schema:
            $ref: "#/definitions/AccountsListResponse"
      tags:
      - accounts
definitions:
  AccountsListResponse:
    type: array
    items:
      $ref: "#/definitions/Account"
  Account:
    type: object
    required:
    - id
    - balance
    - currency
    properties:
      id:
        type: "string"
        description: account's string identifier
      balance:
        description: "balance of account in smallest units of currency.
        For example, for USD it will be cents amount"
        type: integer
      currency:
        description: ticker of currency. For example, for USD
        type: "string"
